/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.serialization.lab.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Menu extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1941912499183819906L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Menu\",\"namespace\":\"com.serialization.lab.avro\",\"fields\":[{\"name\":\"header\",\"type\":\"string\"},{\"name\":\"items\",\"type\":{\"type\":\"array\",\"items\":[\"null\",{\"type\":\"record\",\"name\":\"MenuItem\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"label\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Menu> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Menu> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Menu> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Menu> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Menu> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Menu to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Menu from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Menu instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Menu fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence header;
  private java.util.List<com.serialization.lab.avro.MenuItem> items;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Menu() {}

  /**
   * All-args constructor.
   * @param header The new value for header
   * @param items The new value for items
   */
  public Menu(java.lang.CharSequence header, java.util.List<com.serialization.lab.avro.MenuItem> items) {
    this.header = header;
    this.items = items;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return header;
    case 1: return items;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: header = (java.lang.CharSequence)value$; break;
    case 1: items = (java.util.List<com.serialization.lab.avro.MenuItem>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'header' field.
   * @return The value of the 'header' field.
   */
  public java.lang.CharSequence getHeader() {
    return header;
  }


  /**
   * Sets the value of the 'header' field.
   * @param value the value to set.
   */
  public void setHeader(java.lang.CharSequence value) {
    this.header = value;
  }

  /**
   * Gets the value of the 'items' field.
   * @return The value of the 'items' field.
   */
  public java.util.List<com.serialization.lab.avro.MenuItem> getItems() {
    return items;
  }


  /**
   * Sets the value of the 'items' field.
   * @param value the value to set.
   */
  public void setItems(java.util.List<com.serialization.lab.avro.MenuItem> value) {
    this.items = value;
  }

  /**
   * Creates a new Menu RecordBuilder.
   * @return A new Menu RecordBuilder
   */
  public static com.serialization.lab.avro.Menu.Builder newBuilder() {
    return new com.serialization.lab.avro.Menu.Builder();
  }

  /**
   * Creates a new Menu RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Menu RecordBuilder
   */
  public static com.serialization.lab.avro.Menu.Builder newBuilder(com.serialization.lab.avro.Menu.Builder other) {
    if (other == null) {
      return new com.serialization.lab.avro.Menu.Builder();
    } else {
      return new com.serialization.lab.avro.Menu.Builder(other);
    }
  }

  /**
   * Creates a new Menu RecordBuilder by copying an existing Menu instance.
   * @param other The existing instance to copy.
   * @return A new Menu RecordBuilder
   */
  public static com.serialization.lab.avro.Menu.Builder newBuilder(com.serialization.lab.avro.Menu other) {
    if (other == null) {
      return new com.serialization.lab.avro.Menu.Builder();
    } else {
      return new com.serialization.lab.avro.Menu.Builder(other);
    }
  }

  /**
   * RecordBuilder for Menu instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Menu>
    implements org.apache.avro.data.RecordBuilder<Menu> {

    private java.lang.CharSequence header;
    private java.util.List<com.serialization.lab.avro.MenuItem> items;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.serialization.lab.avro.Menu.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.items)) {
        this.items = data().deepCopy(fields()[1].schema(), other.items);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Menu instance
     * @param other The existing instance to copy.
     */
    private Builder(com.serialization.lab.avro.Menu other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.items)) {
        this.items = data().deepCopy(fields()[1].schema(), other.items);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'header' field.
      * @return The value.
      */
    public java.lang.CharSequence getHeader() {
      return header;
    }


    /**
      * Sets the value of the 'header' field.
      * @param value The value of 'header'.
      * @return This builder.
      */
    public com.serialization.lab.avro.Menu.Builder setHeader(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.header = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'header' field has been set.
      * @return True if the 'header' field has been set, false otherwise.
      */
    public boolean hasHeader() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'header' field.
      * @return This builder.
      */
    public com.serialization.lab.avro.Menu.Builder clearHeader() {
      header = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'items' field.
      * @return The value.
      */
    public java.util.List<com.serialization.lab.avro.MenuItem> getItems() {
      return items;
    }


    /**
      * Sets the value of the 'items' field.
      * @param value The value of 'items'.
      * @return This builder.
      */
    public com.serialization.lab.avro.Menu.Builder setItems(java.util.List<com.serialization.lab.avro.MenuItem> value) {
      validate(fields()[1], value);
      this.items = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'items' field has been set.
      * @return True if the 'items' field has been set, false otherwise.
      */
    public boolean hasItems() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'items' field.
      * @return This builder.
      */
    public com.serialization.lab.avro.Menu.Builder clearItems() {
      items = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Menu build() {
      try {
        Menu record = new Menu();
        record.header = fieldSetFlags()[0] ? this.header : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.items = fieldSetFlags()[1] ? this.items : (java.util.List<com.serialization.lab.avro.MenuItem>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Menu>
    WRITER$ = (org.apache.avro.io.DatumWriter<Menu>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Menu>
    READER$ = (org.apache.avro.io.DatumReader<Menu>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.header);

    long size0 = this.items.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.serialization.lab.avro.MenuItem e0: this.items) {
      actualSize0++;
      out.startItem();
      if (e0 == null) {
        out.writeIndex(0);
        out.writeNull();
      } else {
        out.writeIndex(1);
        e0.customEncode(out);
      }
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.header = in.readString(this.header instanceof Utf8 ? (Utf8)this.header : null);

      long size0 = in.readArrayStart();
      java.util.List<com.serialization.lab.avro.MenuItem> a0 = this.items;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.serialization.lab.avro.MenuItem>((int)size0, SCHEMA$.getField("items").schema());
        this.items = a0;
      } else a0.clear();
      SpecificData.Array<com.serialization.lab.avro.MenuItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.serialization.lab.avro.MenuItem>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.serialization.lab.avro.MenuItem e0 = (ga0 != null ? ga0.peek() : null);
          if (in.readIndex() != 1) {
            in.readNull();
            e0 = null;
          } else {
            if (e0 == null) {
              e0 = new com.serialization.lab.avro.MenuItem();
            }
            e0.customDecode(in);
          }
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.header = in.readString(this.header instanceof Utf8 ? (Utf8)this.header : null);
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<com.serialization.lab.avro.MenuItem> a0 = this.items;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.serialization.lab.avro.MenuItem>((int)size0, SCHEMA$.getField("items").schema());
            this.items = a0;
          } else a0.clear();
          SpecificData.Array<com.serialization.lab.avro.MenuItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.serialization.lab.avro.MenuItem>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.serialization.lab.avro.MenuItem e0 = (ga0 != null ? ga0.peek() : null);
              if (in.readIndex() != 1) {
                in.readNull();
                e0 = null;
              } else {
                if (e0 == null) {
                  e0 = new com.serialization.lab.avro.MenuItem();
                }
                e0.customDecode(in);
              }
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










